apgsga-it/piper

apg-patch-service-cmdclient/src/main/groovy/com/apgsga/patch/service/client/PatchCli.groovy, apg-patch-service-cmdclient/src/test/groovy/com/apgsga/patch/service/client/PatchCloneClientTest.groovy, apg-patch-service-cmdclient/src/test/groovy/com/apgsga/patch/service/client/testRevision.groovy, apg-patch-service-cmdclient/src/test/resources/Revisions.json
Revision.json has been moved into /var/opt/apg-patch-cli folder. RetrieveRevision and SaveRevision have now been moved into apscli.
Careful: this pull request is only to manage the Revision from apscli. The clone problem (JAVA8MIG-353) still have to be done correctly, and will be done as soon as this one will have been approved and merged on master.
=> Java8mig365 centralize revision logic

apg-patch-service-cmdclient/build.gradle, apg-patch-service-cmdclient/packaging/bin/apscli.sh, apg-patch-service-cmdclient/packaging/bin/apsdbcli.sh, apg-patch-service-cmdclient/src/main/groovy/com/apgsga/patch/service/client/db/PatchDbCli.groovy, apg-patch-service-cmdclient/src/main/groovy/pli.groovy, apg-patch-service-cmdclient/src/main/groovy/pliStarter.groovy, apg-patch-service-cmdclient/src/main/resources/apscli.properties, apg-patch-service-cmdclient/src/test/groovy/com/apgsga/patch/service/client/DbCliIntegrationTest.groovy
apscli extended with a new "PatchDbCli" client. This is a first step only specific to JAVA8MIG372, but in the future we could/should write more specific client (for now we weill have PatchCli and PatchDbCli). We also have a new "sh" script in order to start the new client. This new client will however be called from within our code, so it doesn't have any influence on the part which has already been integrated into the clone mechanism.
=> Java8mig372 on clone integration 2

apg-patch-service-server/src/main/java/com/apgsga/microservice/patch/server/impl/EntwicklungInstallationsbereitAction.java
If a patch doesn't contain an Maven Artifact, it will be stuck into "Entwicklung Installationbereit" status. The following is seen in Patch Service log (Look for line starting with WARN):
2018-08-17 10:22:25.173  INFO 3098 --- [http-nio-127.0.0.1-9010-exec-9] c.a.m.p.s.i.GroovyScriptActionExecutor   : With binding:{configDir=file:///etc/opt/apg-patch-common, patchNumber=5741, configFileName=TargetSystemMappings.json, toState=EntwicklungInstallationsbereit, patchContainerBean=com.apgsga.microservice.patch.server.impl.SimplePatchContainerBean@5c5eefef}
2018-08-17 10:22:25.245  INFO 3098 --- [http-nio-127.0.0.1-9010-exec-9] s.i.EntwicklungInstallationsbereitAction : Running EntwicklungInstallationsbereitAction, with: 5741, EntwicklungInstallationsbereit, and parameters: …
=> tag only if vcs patch is not empty

apg-patch-service-cmdclient/src/main/groovy/com/apgsga/patch/service/client/PatchArtifactoryClient.groovy
LIP provided a new script to be called in order to delete Jadas Images which won't be used anymore. 
As discussed, we will call this script at the time we clean our Releases on Artifactory.
What do you think? Do you agree with the place where the script would be called?
(we basically need a "from" and "to" parameters...)
=> Calling OPS Script to delete Jadas Image

apg-patch-service-cmdclient/src/test/groovy/com/apgsga/patch/service/client/DbCliIntegrationTest.groovy
Using a Stub (from Spock Framework) in order to simulate a call to a function.
=> Stub in order to replace call to patchDbCli in Unit Test

apg-patch-artifact-querymanager/src/main/java/com/apgsga/artifact/query/impl/ArtifactsDependencyResolverImpl.java, apg-patch-artifact-querymanager/src/main/java/com/apgsga/artifact/query/impl/PropertyFileBasedVersionManager.java, apg-patch-artifact-querymanager/src/test/groovy/com/apgsga/artifact/query/PropertyFileBasedVersionManagerTests.groovy, apg-patch-artifact-querymanager/src/test/resources/Patch5797.json, apg-patch-service-cmdclient/build.gradle, apg-patch-service-server/build.gradle, build.gradle
Basically Mixin in List<Map<String,String> , which reflect the MavenArtefacts List of Patch*.json after deserializing them with JsonSlurper, The non  SNAPSHOT version from there , overrides those from the dm-bom.
=> Patch Libraries changes to PropertyFileBasedVersionManager

apg-patch-service-cmdclient/packaging/bin/apsrevcli.sh, apg-patch-service-cmdclient/src/main/groovy/com/apgsga/patch/service/client/PatchArtifactoryClient.groovy, apg-patch-service-cmdclient/src/main/groovy/com/apgsga/patch/service/client/PatchCli.groovy, apg-patch-service-cmdclient/src/main/groovy/com/apgsga/patch/service/client/db/PatchDbCli.groovy, apg-patch-service-cmdclient/src/main/groovy/com/apgsga/patch/service/client/db/PatchDbClient.groovy, apg-patch-service-cmdclient/src/main/groovy/com/apgsga/patch/service/client/revision/PatchRevisionCli.groovy, apg-patch-service-cmdclient/src/main/groovy/com/apgsga/patch/service/client/revision/PatchRevisionClient.groovy, apg-patch-service-cmdclient/src/main/groovy/pliStarter.groovy, apg-patch-service-cmdclient/src/test/groovy/com/apgsga/patch/service/client/IntegrationTest.groovy, apg-patch-service-cmdclient/src/test/groovy/com/apgsga/patch/service/client/RevisionCliIntegrationTest.groovy, apg-patch-service-cmdclient/src/test/groovy/com/apgsga/patch/service/client/TestUtil.groovy
Revision tasks have been moved into a specific client. That means, for following target options:
- sr 
- rr 
- pr 
- resr 
- rtr
In this first step, I only moved the tasks to a specific client. Exchanging data via a standard JSON file, eventually setting up a Revision interface etc ... can be done afterwards (I just would like to first test that nothing has been forgotten...)
=> Java8mig 410 move revision options to own cli

apg-patch-service-cmdclient/src/main/groovy/com/apgsga/patch/client/utils/TargetSystemMappings.groovy, apg-patch-service-cmdclient/src/main/groovy/com/apgsga/patch/service/client/PatchCli.groovy, apg-patch-service-cmdclient/src/main/groovy/com/apgsga/patch/service/client/db/PatchDbCli.groovy, apg-patch-service-cmdclient/src/main/groovy/com/apgsga/patch/service/client/db/PatchDbClient.groovy, apg-patch-service-cmdclient/src/test/groovy/com/apgsga/patch/service/client/DbCliIntegrationTest.groovy, apg-patch-service-cmdclient/src/test/groovy/com/apgsga/patch/service/client/PatchCliIntegrationExceptionHandlingTests.groovy, apg-patch-service-cmdclient/src/test/groovy/com/apgsga/patch/service/client/PatchCliIntegrationTest.groovy, apg-patch-service-cmdclient/src/test/resources/config/TargetSystemMappings.json, apg-patch-service-server/src/main/java/com/apgsga/microservice/patch/server/impl/jenkins/JenkinsClientImpl.java, build.gradle
Refactored PatchDbCli - quite alot, thank god for the tests ;-) 
- All jdbc calls to the are now supported with PatchDbCli
- Moved the -sta Db Code of  PatchCli to here 
- Moved all application code to PatchDbClient , also listPatchAfterClone
- Added an option for Restart support for querying predecssor States, this not yet used and finished
- Refactored DbCliIntegrationTest.groovy to support conditional Testing against the Db , see @Requires option of Spock
- Cleaned up PatchDbcli and PatchCli some
- Important: Refactored so  that PatchDbCli doesn't write in ther normal execution path to stdout, needs to be asserted in the tests yet 
- So the assumption is that Standardout can be used for simple cases , see https://issues.jenkins-ci.org/browse/JENKINS-26133
@apgsga-jhe  i will be merging …
=> Preparation for Restarting Patch Pipeline

apg-patch-service-cmdclient/build.gradle, apg-patch-service-cmdclient/src/main/groovy/com/apgsga/patch/service/client/db/PatchDbCli.groovy, apg-patch-service-cmdclient/src/main/groovy/com/apgsga/patch/service/client/db/PatchDbClient.groovy, apg-patch-service-cmdclient/src/main/groovy/com/apgsga/patch/service/client/utils/TargetSystemMappings.groovy, apg-patch-service-cmdclient/src/test/groovy/com/apgsga/patch/service/client/DbCliIntegrationTest.groovy
I changed to logic for redo support. 
Now, PatchDbCli returns to actual State which has to be redone, instead of the predessor States. See also Jenkins Patch Pipeline
@apgsga-jhe FYI, i am going ahead with merge and testing
=> Redo redesign

apg-patch-artifact-querymanager/src/main/java/com/apgsga/artifact/query/impl/RepositorySystemFactory.java, apg-patch-service-client/src/main/java/com/apgsga/microservice/patch/client/MicroservicePatchClient.java, apg-patch-service-cmdclient/build.gradle, apg-patch-service-cmdclient/packaging/profile/apscli.sh, apg-patch-service-cmdclient/src/main/groovy/com/apgsga/patch/service/client/PatchArtifactoryClient.groovy, apg-patch-service-cmdclient/src/main/resources/apscli.properties, apg-patch-service-server/build.gradle, build.gradle, gradle.properties
The Artifactory Read-only User Password is available as Environment Variable: REPO_RO_PASSWD, instead of property value.  It is evaluated at Build time resp. Runtime . Developers need to add this Variable to their enviroments. 
In Jenkins it is configured as "Globale Eigentschaft", see https://jenkins.apgsga.ch/configure
=> Hide password for dev artifactory user

apg-patch-service-cmdclient/src/main/groovy/com/apgsga/patch/service/client/db/PatchDbCli.groovy, apg-patch-service-cmdclient/src/main/groovy/com/apgsga/patch/service/client/db/PatchDbClient.groovy, apg-patch-service-cmdclient/src/test/groovy/com/apgsga/patch/service/client/DbCliIntegrationTest.groovy, apg-patch-service-common/src/main/java/com/apgsga/microservice/patch/api/Patch.java, apg-patch-service-common/src/main/java/com/apgsga/microservice/patch/api/impl/PatchBean.java
The restart mechanism of the Patch Pipeline now saves the state of PatchConfig into Patch*.json file of the a Patch newly also before the execution of a Stage. In case of a failure of the Pipeline the target redo State is taken from PatchConfig: targetToState.
This makes any db query for the state and targetToState of a Patch unnecessary. Respective code has been eliminated. 
Also the necessary attribute targetToState has been added to Patch
=> Redo without db Query

apg-patch-service-cmdclient/packaging/conf/application.properties, apg-patch-service-cmdclient/src/main/groovy/com/apgsga/patch/service/client/PatchArtifactoryClient.groovy, apg-patch-service-cmdclient/src/test/resources/config/app-test.properties
We don't need to call the "/opt/apgops/cleanup_jadas_images_by_revision.sh" OPS script anymore. In theory, we will be able to delete the RPMs just like we do for other resources in other repositories.
@chhex : I'll quickly merge this one, this serves more as for FYI .... If then something doesn't work during my tests, I'll fix directly on master.
=> Java8mig583 clean rpm patch

apg-patch-service-server/src/main/java/com/apgsga/microservice/patch/server/impl/jenkins/JenkinsClientImpl.java, apg-patch-service-server/src/main/resources/messages.properties, build.gradle
I still need to test on Jenkins-t, but as for the other Pull Request, early feedback are welcome.
Basically nothing complicated, instead of looping and waiting on the job to start, simply submit and return. Probably the "triggerPipelineJobWithoutWaitingOnFeedback" doesn't necessarily needs to be synchronized, but it also won't hurt.
=> JAVA8MIG-680 - Not waiting on feedback when submitting onDemand Job.

apg-patch-service-cmdclient/src/main/groovy/com/apgsga/patch/service/client/PatchServiceClient.groovy, apg-patch-service-cmdclient/src/main/groovy/com/apgsga/patch/service/client/db/PatchDbClient.groovy, apg-patch-service-cmdclient/src/test/groovy/com/apgsga/patch/service/client/PatchCliIntegrationTest.groovy, apg-patch-service-server/src/main/java/com/apgsga/microservice/patch/server/impl/jenkins/JenkinsMockClient.java
Not sure the pull request name is 100% right ... is it really related with JAVA8MIG-730 ... but ok, detail...
- Calling onClone pipeline with target specific name
- Catching exception when fetching list of patches to be reinstalled and printing "true"/"false" on stdout in order for the caller to catch the result.
(- Ignoring one test as it still needs to be adapted for JAVA8MIG-725...)
=> separated onclone pipeline for each target

apg-patch-service-server/src/main/java/com/apgsga/microservice/patch/server/impl/SimplePatchContainerBean.java, apg-patch-service-server/src/main/java/com/apgsga/microservice/patch/server/impl/jenkins/JenkinsClient.java, apg-patch-service-server/src/main/java/com/apgsga/microservice/patch/server/impl/jenkins/JenkinsClientImpl.java, apg-patch-service-server/src/main/java/com/apgsga/microservice/patch/server/impl/jenkins/JenkinsMockClient.java, apg-patch-service-server/src/main/resources/messages.properties
In order not to have unwanted behaviors, I kept the pre-condition with the "failed" pipeline, but added as well the "aborted" scenario.
What do you guys think? 
Ideally we could patch this one together with JAVA8MIG-732, where we'll anyway have to install a new version of Piper.
=> java8mig-747 / Preconditions to allow redo of aborted Pipelines

apg-patch-service-client/src/main/java/com/apgsga/microservice/patch/client/MicroservicePatchClient.java, apg-patch-service-client/src/test/java/com/apgsga/microservice/patch/client/MicroServicePatchClientTest.java, apg-patch-service-cmdclient/src/main/groovy/com/apgsga/patch/service/client/PatchServiceClient.groovy, apg-patch-service-common/src/main/java/com/apgsga/microservice/patch/api/PatchPersistence.java, apg-patch-service-common/src/main/java/com/apgsga/microservice/patch/api/PatchService.java, apg-patch-service-server/src/main/java/com/apgsga/microservice/patch/server/MicroServicePatchController.java, apg-patch-service-server/src/main/java/com/apgsga/microservice/patch/server/PatchOpServiceController.java, apg-patch-service-server/src/main/java/com/apgsga/microservice/patch/server/impl/SimplePatchContainerBean.java, apg-patch-service-server/src/main/java/com/apgsga/microservice/patch/server/impl/persistence/FilebasedPatchPersistence.java, apg-patch-service-server/src/test/java/com/apgsga/microservice/patch/server/MicroServicePatchServerTest.java, apg-patch-service-server/src/test/java/com/apgsga/microservice/patch/server/impl/persistence/FilebasedPersistenceTest.java
Ability to get list of Patches containing a given module name. Module can either be a Java Artifact of a DB Module.
As in code commented, we might want to change on which field the research will be made, this can easily be change. For now, the research would be done:
- On ArtifactId for MavenArtifact objects
- On ModuleName for DBObject
GUI will obviously also have to be updated, but this one can (has to) go in production first.
=> java8mig-748 / IT21-CM-GUI: Suche nach bestimmten Java-Artifakten

apg-patch-service-cmdclient/src/main/groovy/com/apgsga/patch/service/client/revision/PatchRevisionCli.groovy, apg-patch-service-cmdclient/src/main/groovy/com/apgsga/patch/service/client/revision/PatchRevisionClient.groovy, apg-patch-service-cmdclient/src/test/groovy/com/apgsga/patch/service/client/RevisionCliIntegrationTest.groovy
This is a requirement for ARCH-42, where we need to get all the revisions which have been installed on Production. 
This has been successfully tested on jenkins-t, with for example following command:
`apsrevcli.sh -gr dev-ondemand`
=> ARCH-96 / Liste von "Revisions" für ein bestimmten Umgebung

apg-patch-service-server/src/main/java/com/apgsga/microservice/patch/server/impl/persistence/FilebasedPatchPersistence.java, build.gradle
"savePatch" and "savePatchLog" are 2 different methods which are calling the same function in order to write content in 2 different files. 
We had the case where "savePatch" was trying to write into the patchLog file ... see also the stacktrace within https://jira.apgsga.ch/browse/CM-226
=> CM-226 / concurrency problem

apg-patch-service-api/src/main/java/com/apgsga/microservice/patch/api/JenkinsParameterType.java, apg-patch-service-api/src/main/java/com/apgsga/microservice/patch/api/PatchOpService.java, apg-patch-service-cmdclient/src/main/groovy/com/apgsga/patch/service/client/PatchCli.groovy, apg-patch-service-cmdclient/src/main/groovy/com/apgsga/patch/service/client/rest/PatchRestServiceClient.groovy, apg-patch-service-cmdclient/src/test/groovy/com/apgsga/patch/service/client/PatchCliIntegrationTest.groovy, apg-patch-service-core/src/main/java/com/apgsga/microservice/patch/core/commands/jenkins/ssh/JenkinsSshBuildJobCmd.java, apg-patch-service-core/src/main/java/com/apgsga/microservice/patch/core/commands/jenkins/ssh/JenkinsSshCommand.java, apg-patch-service-core/src/main/java/com/apgsga/microservice/patch/core/commands/jenkins/ssh/JenkinsSshStopBuildCmd.java, apg-patch-service-core/src/main/java/com/apgsga/microservice/patch/core/impl/SimplePatchContainerBean.java, apg-patch-service-core/src/main/java/com/apgsga/microservice/patch/core/impl/jenkins/JenkinsClient.java, apg-patch-service-core/src/main/java/com/apgsga/microservice/patch/core/impl/jenkins/JenkinsClientImpl.java, apg-patch-service-core/src/main/java/com/apgsga/microservice/patch/core/impl/jenkins/JenkinsMockClient.java, apg-patch-service-core/src/test/java/com/apgsga/microservice/patch/core/commands/jenkins/ssh/test/JenkinsCliBaseTest.java, apg-patch-service-core/src/test/java/com/apgsga/microservice/patch/core/commands/jenkins/ssh/test/JenkinsSshCommandsTest.java, apg-patch-service-server/src/main/java/com/apgsga/microservice/patch/server/PatchOpServiceController.java, build.gradle
In scope of IT-36392, we need to be able to start a Job with a file as parameter. This was so far not supported by apscli. I had to refactor a bit our SSHJenkinsCommand part, because of a crazy problem with Linux pipe and Java ProcessBuilder.
The problem was similar to this one, but with "cat" command: https://stackoverflow.com/questions/3776195/using-java-processbuilder-to-execute-a-piped-command
Note that the current implementation doesn't support to sart a job which would have both string and file parameters, but I don't believe this is a scenario we have to support now.
Ideally, I would like to quickly merge this one.
=> IT-36392 / apscli, start a job with file parameter

apg-patch-service-api/src/main/java/com/apgsga/microservice/patch/api/Patch.java, apg-patch-service-client/src/test/java/com/apgsga/microservice/patch/client/MicroServicePatchClientTest.java, apg-patch-service-core/src/main/java/com/apgsga/microservice/patch/core/impl/SimplePatchContainerBean.java, apg-patch-service-server/src/test/java/com/apgsga/microservice/patch/core/MicroServicePatchServerTest.java, build.gradle
@chhex, @apgsga-uge  : I'll probably merge this one quickly. I believe the important point to noticed is within SimplePatchContainerBean, where we save the info only when the patch does not exist. That means, we cannot change the stageMappings for an existing Patch, which I believe makes sense ... but yep, we could discuss it.
=> IT-36392 / stageMapping saved within Patch object

apg-patch-service-core/src/main/java/com/apgsga/microservice/patch/core/impl/SimplePatchContainerBean.java
listAllObjectsChangedForDbModule method was absolutely not doing its job.
The aim of this method is to return DBModule for which a change has been made on the db patch branch.
=> IT-36838 /  listAllObjectsChangedForDbModule method not doing its job

apg-patch-service-core/src/main/java/com/apgsga/microservice/patch/core/impl/jenkins/JenkinsClientImpl.java, apg-patch-service-core/src/main/java/com/apgsga/microservice/patch/core/impl/jenkins/TaskStartOnClonePipeline.java
@apgsga-jhe 
See IT-36966:  patchserver-setup should create pre-defined onClone pipeline jobs.
Basically now the Clone Pipeline is started with the GenericJobBuilder per Target.  This way , we have all Target specific Jobs started via GenericJobBuilder with the same Naming Convention, which makes the ordering by Timestamp easy and also the filtering of Jobs per Target. 
See this as discussable proposition 
@apgsga-uge  FYI
=> TaskStartOnClonePipeline started with GenericJobBuilder

apg-patch-service-core/src/main/java/com/apgsga/microservice/patch/core/commands/JschCommandRunner.java, apg-patch-service-core/src/main/java/com/apgsga/microservice/patch/core/impl/SimplePatchContainerBean.java, apg-patch-service-server/packaging/metaInfoDb/DbModules.json
When saving a brand new patch, we first check if the DB Branch has to be created or not. 
DB Branches will be created in advance, see also Ticket CM-328.
I also took the opportunity to rename the branch prefix from "Patch_" to "Ms_patch_" ... to ensure we will be able to differentiate between old/new branches ...
@chhex , @apgsga-uge : Ideally I would like to merge this one before restarting an installation on appl-patch.apgsga.ch
=> IT-37027 / Piper should not always create a new CVS DB Branch

apg-patch-service-core/src/main/java/com/apgsga/microservice/patch/core/impl/PatchSetupTask.java, apg-patch-service-core/src/main/java/com/apgsga/microservice/patch/core/impl/jenkins/InstallDbObjectsInfos.java, apg-patch-service-core/src/main/java/com/apgsga/microservice/patch/core/impl/jenkins/InstallPipelineParameter.java, apg-patch-service-core/src/main/java/com/apgsga/microservice/patch/core/impl/jenkins/JenkinsClientImpl.java, apg-patch-service-core/src/main/java/com/apgsga/microservice/patch/core/impl/jenkins/JenkinsPipelinePreprocessor.java
We need additional information to be passed to the install pipeline in order to merge the DB-Objects back on the prod branch for patches which have be install to production.
=> IT-37121 / verify that DB-module are merged back on prod branch when patch is in production

apg-patch-service-core/src/main/java/com/apgsga/microservice/patch/core/impl/jenkins/BuildPipelineParameter.java, apg-patch-service-core/src/main/java/com/apgsga/microservice/patch/core/impl/jenkins/OnCloneBuildParameters.java, apg-patch-service-core/src/main/java/com/apgsga/microservice/patch/core/impl/jenkins/OnDemandPipelineParameter.java, apg-patch-service-core/src/main/java/com/apgsga/microservice/patch/core/impl/jenkins/TaskStartBuildPipeline.java, apg-patch-service-core/src/main/java/com/apgsga/microservice/patch/core/impl/jenkins/TaskStartOnClonePipeline.java, apg-patch-service-core/src/main/java/com/apgsga/microservice/patch/core/impl/jenkins/TaskStartOnDemandPipeline.java
@chhex , @apgsga-uge : FYI, one which I'll merge immediately.
We need to differentiate the artifacts which have to be built with ones which only have to be assemble (framework-libraries, for example)
=> IT-37075 / test a patch with framework library
