apg-patch-service-client/src/main/java/com/apgsga/microservice/patch/client/MicroservicePatchClient.java, apg-patch-service-cmdclient/build.gradle, apg-patch-service-cmdclient/src/main/groovy/com/apgsga/patch/service/client/PatchCli.groovy, apg-patch-service-cmdclient/src/main/groovy/com/apgsga/patch/service/client/PatchServiceClient.groovy, apg-patch-service-server/build.gradle, apg-patch-service-server/src/main/java/com/apgsga/microservice/patch/server/MicroServicePatchController.java, apg-patch-service-server/src/main/java/com/apgsga/microservice/patch/server/PatchOpServiceController.java, build.gradle
changed url's to
patch/public
and
patch/private
=> JAVA8MIG-265

apg-patch-service-client/src/main/java/com/apgsga/microservice/patch/client/MicroservicePatchClient.java, apg-patch-service-client/src/test/java/com/apgsga/microservice/patch/client/MicroServicePatchClientTest.java, apg-patch-service-common/src/main/java/com/apgsga/microservice/patch/api/PatchService.java, apg-patch-service-server/src/main/java/com/apgsga/microservice/patch/server/MicroServicePatchController.java, apg-patch-service-server/src/main/java/com/apgsga/microservice/patch/server/impl/SimplePatchContainerBean.java
This is what's required on service side regarding JAVA8MIG-379. Basically only a new "findByIds" method.
=> findyByIds added

apg-patch-service-common/src/main/java/com/apgsga/microservice/patch/api/Patch.java, apg-patch-service-common/src/main/java/com/apgsga/microservice/patch/api/impl/PatchBean.java
Quick branch to check the "piper side" for JAVA8MIG-381. On this side, it shouldn't be anything else that persisting the "forceJadasInstallation" property.
The other things will (probably) be managed on GUI side.
=> "forceJadasInstallation" persisted

apg-patch-service-common/src/main/java/com/apgsga/microservice/patch/api/Patch.java, apg-patch-service-common/src/main/java/com/apgsga/microservice/patch/api/impl/PatchBean.java, build.gradle
A quick one related with https://github.com/apgsga-it/jenkins-patch-scripts/pull/12
Do you see things as well like this, or am I missing something?
=> Manage "installJadas" field within patchBean

apg-patch-service-cmdclient/src/main/groovy/com/apgsga/patch/service/client/PatchRevisionClient.groovy
Very minor ... but just to be sure I'm not missing anything obvious? 
I don't believe we need to change anything at any other place. Basically, the only involved function should be the one where we look for the Prod Revision.
=> Searching for target.name instead of target.typeInd

apg-patch-artifact-querymanager/src/main/java/com/apgsga/artifact/query/ArtifactVersionManager.java, apg-patch-artifact-querymanager/src/main/java/com/apgsga/artifact/query/impl/PropertyFileBasedVersionManager.java, apg-patch-artifact-querymanager/src/test/groovy/com/apgsga/artifact/query/PropertyFileBasedVersionManagerTests.groovy, apg-patch-service-common/src/main/resources/messages.properties, build.gradle
Some changes, which facilitate integration in gradle builds.
@apgsga-jhe  Made this branch for your information , going ahead with merging it
=> Api directly on Patchfile path

apg-patch-service-cmdclient/src/main/groovy/com/apgsga/patch/service/client/revision/PatchRevisionCli.groovy, apg-patch-service-cmdclient/src/main/groovy/com/apgsga/patch/service/client/revision/PatchRevisionClient.groovy, apg-patch-service-cmdclient/src/test/groovy/com/apgsga/patch/service/client/RevisionCliIntegrationTest.groovy
@chhex : JFYI ... I'll merge it immediately
=> Java8mig 410 new revision client 2

apg-patch-artifact-querymanager/src/main/resources/templatePersistence.json, apg-patch-artifact-querymanager/src/test/groovy/com/apgsga/artifact/query/ArtifactManagerTests.groovy, apg-patch-artifact-querymanager/src/test/resources/templatePersistence.json, apg-patch-service-common/src/main/java/com/apgsga/microservice/patch/api/PatchService.java, build.gradle
Following has been added to templatePersistence.json:
{
"groupId": "com.affichage.persistence.java.service",
"artifactId": "tests-javaservices",
"name": null,
"version": "",
"className": "com.apgsga.microservice.patch.api.impl.MavenArtifactBean",
"dependencyLevel": 0
}
Version bumped up.
=> JAVA8MIG-519

apg-patch-service-server/packaging/service/apg-patch-service-server.service
A quick one as "sanity check"... All good?
=> JAVA8MIG-522: JVM Opt for patch-service

apg-patch-service-server/build.gradle
Master is mainstream development
=> 1.2.x Merge

apg-patch-service-common/src/main/java/com/apgsga/microservice/patch/api/Patch.java, apg-patch-service-common/src/main/java/com/apgsga/microservice/patch/api/impl/PatchBean.java, build.gradle
Neues Feld in Patch: lastPipelineTask, siehe auch https://github.com/apgsga-it/jenkins-patch-scripts/pull/47
=> JAVA8MIG-742 last successful Pipeline Task field on API

apg-patch-service-common/src/main/java/com/apgsga/microservice/patch/api/impl/PatchBean.java
non-configurative approach as first implementation
=> default Branch now "prod" instead of "HEAD"

apg-patch-service-server/src/main/java/com/apgsga/microservice/patch/server/impl/jenkins/JenkinsClientImpl.java
more logging to find cause of onClone problems
=> 1.3.x.BETR-21986

apg-patch-service-cmdclient/src/main/groovy/com/apgsga/patch/service/client/revision/PatchRevisionCli.groovy, apg-patch-service-cmdclient/src/main/groovy/com/apgsga/patch/service/client/revision/PatchRevisionClient.groovy, apg-patch-service-cmdclient/src/test/groovy/com/apgsga/patch/service/client/DbCliIntegrationTest.groovy, apg-patch-service-cmdclient/src/test/groovy/com/apgsga/patch/service/client/RevisionCliIntegrationTest.groovy, build.gradle
Correctly tested on jenkins-t ..... sorry for the previous attempt, this ne should be the last pull request for this topic ...
=> ARCH-101 / apsrevcli - delete Revisions-Liste für einen Target

apg-patch-service-cmdclient/src/main/groovy/com/apgsga/patch/service/client/PatchArtifactoryClient.groovy, build.gradle
When cloning from onClone Pipeline, apscli is getting called with "cr" option (Clean Releases). We had an issue in the way we were looking for Artifacts on Artifactory, and therefore some Artifacts would never have been deleted.
=> CM-232 / Better clean Artifactory

apg-patch-service-cmdclient/src/main/groovy/com/apgsga/patch/service/client/PatchArtifactoryClient.groovy
"sources" JARs not found in our requests
=> CM-243 / sources JARs added in search of Artifacts to be deleted

apg-patch-service-client/src/main/java/com/apgsga/microservice/patch/client/MicroservicePatchClient.java, apg-patch-service-common/src/main/java/com/apgsga/microservice/patch/api/PatchService.java, apg-patch-service-server/src/main/java/com/apgsga/microservice/patch/server/MicroServicePatchController.java, apg-patch-service-server/src/main/java/com/apgsga/microservice/patch/server/impl/SimplePatchContainerBean.java, apg-patch-service-server/src/main/java/com/apgsga/microservice/patch/server/impl/vcs/CheckoutModulesInFolderCmd.java, apg-patch-service-server/src/main/java/com/apgsga/microservice/patch/server/impl/vcs/PatchVcsCommand.java, build.gradle
Provide possibility to list all SQL Files for a CVS Module on a patch Branch, even if no changes have been found.
=> IT-34991 / IT21 cm-ui, SQL Objekte brauchen Anpassungen um selektierbar zu sein

apg-patch-service-api/src/main/java/com/apgsga/microservice/patch/api/PatchOpService.java, apg-patch-service-cmdclient/src/main/groovy/com/apgsga/patch/service/client/PatchCli.groovy, apg-patch-service-cmdclient/src/main/groovy/com/apgsga/patch/service/client/config/PliConfig.java, apg-patch-service-cmdclient/src/main/groovy/com/apgsga/patch/service/client/db/PatchDbCli.groovy, apg-patch-service-cmdclient/src/main/groovy/com/apgsga/patch/service/client/db/PatchDbClient.groovy, apg-patch-service-cmdclient/src/main/groovy/com/apgsga/patch/service/client/rest/PatchRestServiceClient.groovy, apg-patch-service-cmdclient/src/main/groovy/com/apgsga/patch/service/client/serverless/PatchServerlessImpl.groovy, apg-patch-service-cmdclient/src/test/groovy/com/apgsga/patch/service/client/DbCliIntegrationTest.groovy, apg-patch-service-cmdclient/src/test/groovy/com/apgsga/patch/service/client/PatchCliIntegrationTest.groovy, apg-patch-service-cmdclient/src/test/resources/config/app-test.properties, apg-patch-service-core/src/main/java/com/apgsga/microservice/patch/core/impl/SimplePatchContainerBean.java, apg-patch-service-core/src/main/java/com/apgsga/microservice/patch/core/impl/jenkins/JenkinsClient.java, apg-patch-service-core/src/main/java/com/apgsga/microservice/patch/core/impl/jenkins/JenkinsClientImpl.java, apg-patch-service-core/src/main/java/com/apgsga/microservice/patch/core/impl/jenkins/JenkinsMockClient.java, apg-patch-service-server/src/main/java/com/apgsga/microservice/patch/server/PatchOpServiceController.java, apg-patch-service-server/src/main/resources/messages.properties, apg-patch-service-server/src/test/java/com/apgsga/microservice/patch/core/MicroServicePatchServerTest.java
So basically we'll be able to:
- Start the assembleAndDeploy Pipelines using apscli.
- The pipeline will be able to call apsdbcli in order to copy the required json file into a dest folder
@chhex : would you have time for a first quick review?
=> IT-35954 : Piper API and pre-requisites to start "assemble and deploy" pipeline

apg-patch-service-cmdclient/src/main/groovy/com/apgsga/patch/service/client/PatchCli.groovy, apg-patch-service-cmdclient/src/test/groovy/com/apgsga/patch/service/client/PatchCliIntegrationTest.groovy
@chhex : I'll probably merge this one immediately. Basically, I'm now not doing a "Files.copy" anymore, but calling an internal method (which existed before) from apscli, which then calls our API.
=> IT-36032 / apscli should call API when copying Patch JSON files

apg-patch-service-api/src/main/java/com/apgsga/microservice/patch/api/PatchOpService.java, apg-patch-service-api/src/main/java/com/apgsga/microservice/patch/api/PatchService.java, apg-patch-service-client/src/main/java/com/apgsga/microservice/patch/client/MicroservicePatchClient.java, apg-patch-service-cmdclient/src/main/groovy/com/apgsga/patch/service/client/PatchCli.groovy, apg-patch-service-cmdclient/src/main/groovy/com/apgsga/patch/service/client/rest/PatchRestServiceClient.groovy, apg-patch-service-cmdclient/src/test/groovy/com/apgsga/patch/service/client/PatchCliIntegrationTest.groovy, apg-patch-service-core/src/main/java/com/apgsga/microservice/patch/core/impl/SimplePatchContainerBean.java, apg-patch-service-core/src/main/java/com/apgsga/microservice/patch/core/impl/jenkins/JenkinsClient.java, apg-patch-service-core/src/main/java/com/apgsga/microservice/patch/core/impl/jenkins/JenkinsClientImpl.java, apg-patch-service-core/src/main/java/com/apgsga/microservice/patch/core/impl/jenkins/JenkinsMockClient.java, apg-patch-service-server/src/main/java/com/apgsga/microservice/patch/server/MicroServicePatchController.java, apg-patch-service-server/src/main/java/com/apgsga/microservice/patch/server/PatchOpServiceController.java, apg-patch-service-server/src/main/resources/messages.properties, apg-patch-service-server/src/test/java/com/apgsga/microservice/patch/core/MicroServicePatchServerTest.java
@chhex : One which shouldn't be complicated (hopefully ;) ).
Basically the Piper APIs in order to start our future "install" Pipelines.
=> IT- 35961 / Job Preconditions and Submit API for install pipeline

apg-patch-service-server/packaging/conf/application.properties
@apgsga-jhe  Can you check and merge this , in context of IT-36397
=> Default Application Properties for Package

apg-patch-service-core/src/main/java/com/apgsga/microservice/patch/core/impl/SimplePatchContainerBean.java
@chhex  : And here another small one, so that we can also search patches containing a specific docker service.
=> IT-36840 / extending findWithObjectName to docker service names

apg-patch-service-api/src/main/java/com/apgsga/microservice/patch/api/OnDemandParameter.java, apg-patch-service-api/src/main/java/com/apgsga/microservice/patch/api/PatchOpService.java, apg-patch-service-cmdclient/src/main/groovy/com/apgsga/patch/service/client/PatchCli.groovy, apg-patch-service-cmdclient/src/main/groovy/com/apgsga/patch/service/client/rest/PatchRestServiceClient.groovy, apg-patch-service-cmdclient/src/test/groovy/com/apgsga/patch/service/client/PatchCliIntegrationTest.groovy, apg-patch-service-core/src/main/java/com/apgsga/microservice/patch/core/impl/SimplePatchContainerBean.java, apg-patch-service-core/src/main/java/com/apgsga/microservice/patch/core/impl/jenkins/AssembleAndDeployPipelineParameter.java, apg-patch-service-core/src/main/java/com/apgsga/microservice/patch/core/impl/jenkins/InstallPipelineParameter.java, apg-patch-service-core/src/main/java/com/apgsga/microservice/patch/core/impl/jenkins/JenkinsClient.java, apg-patch-service-core/src/main/java/com/apgsga/microservice/patch/core/impl/jenkins/JenkinsClientImpl.java, apg-patch-service-core/src/main/java/com/apgsga/microservice/patch/core/impl/jenkins/JenkinsMockClient.java, apg-patch-service-core/src/main/java/com/apgsga/microservice/patch/core/impl/jenkins/JenkinsPipelinePreprocessor.java, apg-patch-service-core/src/main/java/com/apgsga/microservice/patch/core/impl/jenkins/OnDemandPipelineParameter.java, apg-patch-service-core/src/main/java/com/apgsga/microservice/patch/core/impl/jenkins/PackagerInfo.java, apg-patch-service-core/src/main/java/com/apgsga/microservice/patch/core/impl/jenkins/TaskStartOnDemandPipeline.java, apg-patch-service-server/src/main/java/com/apgsga/microservice/patch/server/PatchOpServiceController.java, apg-patch-service-server/src/test/java/com/apgsga/microservice/patch/core/MicroServicePatchServerTest.java
Possibility to start an onDemand pipeline for a given target.
=> IT-35966 / onDemand Pipeline

apg-patch-service-api/src/main/java/com/apgsga/microservice/patch/api/PatchService.java, apg-patch-service-client/src/main/java/com/apgsga/microservice/patch/client/MicroservicePatchClient.java, apg-patch-service-client/src/test/java/com/apgsga/microservice/patch/client/MicroServicePatchClientTest.java, apg-patch-service-core/src/main/java/com/apgsga/microservice/patch/core/impl/SimplePatchContainerBean.java, apg-patch-service-server/src/main/java/com/apgsga/microservice/patch/server/MicroServicePatchController.java
@chhex , @apgsga-uge 
FYI, here also a quick one which I'll merge immediately. With my previous request for IT-35966, I forgot to add the possibility for the MicroservicePatchClient to start an onDemand Pipeline as well, which we need from the GUI ...
=> IT-35966 / start onDemand Pipeline from MicroservicePatchClient

apg-patch-service-api/src/main/java/com/apgsga/microservice/patch/api/OnCloneParameters.java, apg-patch-service-api/src/main/java/com/apgsga/microservice/patch/api/PatchOpService.java, apg-patch-service-cmdclient/src/main/groovy/com/apgsga/patch/service/client/PatchCli.groovy, apg-patch-service-cmdclient/src/main/groovy/com/apgsga/patch/service/client/rest/PatchRestServiceClient.groovy, apg-patch-service-cmdclient/src/test/groovy/com/apgsga/patch/service/client/PatchCliIntegrationTest.groovy, apg-patch-service-core/src/main/java/com/apgsga/microservice/patch/core/impl/SimplePatchContainerBean.java, apg-patch-service-core/src/main/java/com/apgsga/microservice/patch/core/impl/jenkins/JenkinsClient.java, apg-patch-service-core/src/main/java/com/apgsga/microservice/patch/core/impl/jenkins/JenkinsClientImpl.java, apg-patch-service-core/src/main/java/com/apgsga/microservice/patch/core/impl/jenkins/JenkinsMockClient.java, apg-patch-service-core/src/main/java/com/apgsga/microservice/patch/core/impl/jenkins/OnCloneAssembleAndDeployParameter.java, apg-patch-service-core/src/main/java/com/apgsga/microservice/patch/core/impl/jenkins/OnCloneBuildParameters.java, apg-patch-service-core/src/main/java/com/apgsga/microservice/patch/core/impl/jenkins/OnClonePatchParameters.java, apg-patch-service-core/src/main/java/com/apgsga/microservice/patch/core/impl/jenkins/OnClonePipelineParameter.java, apg-patch-service-core/src/main/java/com/apgsga/microservice/patch/core/impl/jenkins/TaskStartOnClonePipeline.java, apg-patch-service-server/src/main/java/com/apgsga/microservice/patch/server/PatchOpServiceController.java, apg-patch-service-server/src/test/java/com/apgsga/microservice/patch/core/MicroServicePatchServerTest.java
Provide possibility to start an onClone pipeline with specific parameters.
=> IT-35965 / Clone pipeline

apg-patch-service-core/src/main/java/com/apgsga/microservice/patch/core/impl/PatchSetupTask.java, apg-patch-service-core/src/main/java/com/apgsga/microservice/patch/core/impl/SimplePatchContainerBean.java, apg-patch-service-server/packaging/conf/application_properties.initial
DB module will be splitted into chunks in order to have smaller command send over ssh.
@apgsga-uge : FYI
=> CM-398 : Tagging Problem beim grossen Patch
